
void com.gini.iordache.services.impl.order.ServiceOrderServiceImpl.createServiceOrder(ServiceOrder) Vehicle not selected at order creation 02-04-2021 21:10:25
void com.gini.iordache.services.impl.order.ServiceOrderServiceImpl.createServiceOrder(ServiceOrder) Vehicle not selected at order creation 02-04-2021 21:10:25
void com.gini.iordache.services.impl.order.ServiceOrderServiceImpl.createServiceOrder(ServiceOrder) Vehicle not selected at order creation 02-04-2021 21:11:08
Future com.gini.iordache.services.impl.user.UserServiceImpl.createUser(User) User already exists 03-04-2021 00:46:45
Future com.gini.iordache.services.impl.user.UserServiceImpl.createUser(User) User already exists 03-04-2021 00:48:39
Future com.gini.iordache.services.impl.user.UserServiceImpl.createUser(User) User already exists 03-04-2021 00:50:07
Future com.gini.iordache.services.impl.user.UserServiceImpl.createUser(User) User already exists 03-04-2021 00:53:56
int com.gini.iordache.services.impl.order.ServiceOrderServiceImpl.closeOrder(ServiceOrder,double,double) Order is already CLOSED 03-04-2021 01:40:40
int com.gini.iordache.services.impl.order.ServiceOrderServiceImpl.closeOrder(ServiceOrder,double,double) Order is already CLOSED 03-04-2021 01:40:52
int com.gini.iordache.services.impl.order.ServiceOrderServiceImpl.closeOrder(ServiceOrder,double,double) Order is already CLOSED 03-04-2021 01:41:08
int com.gini.iordache.services.impl.order.ServiceOrderServiceImpl.closeOrder(ServiceOrder,double,double) Order is already CLOSED 03-04-2021 01:45:01
int com.gini.iordache.services.impl.order.ServiceOrderServiceImpl.closeOrder(ServiceOrder,double,double) Order is already CLOSED 03-04-2021 01:48:25
int com.gini.iordache.services.impl.order.ServiceOrderServiceImpl.closeOrder(ServiceOrder,double,double) Order is already CLOSED 03-04-2021 01:51:23
Authentication ro.gini.iordache.security.provider.UserNamePasswordProvider.authenticate(Authentication) Bad Credential Exception 03-04-2021 22:38:52
Authentication ro.gini.iordache.security.provider.UserNamePasswordProvider.authenticate(Authentication) Bad Credential Exception 03-04-2021 22:39:12
Authentication ro.gini.iordache.security.provider.UserNamePasswordProvider.authenticate(Authentication) Bad Credential Exception 03-04-2021 22:39:39
Authentication ro.gini.iordache.security.provider.UserNamePasswordProvider.authenticate(Authentication) Bad Credential Exception 03-04-2021 22:40:35
Authentication ro.gini.iordache.security.provider.UserNamePasswordProvider.authenticate(Authentication) Bad Credential Exception 03-04-2021 22:41:18
Authentication ro.gini.iordache.security.provider.UserNamePasswordProvider.authenticate(Authentication) Bad Credential Exception 03-04-2021 22:41:52
Authentication ro.gini.iordache.security.provider.UserNamePasswordProvider.authenticate(Authentication) Bad Credential Exception 03-04-2021 22:42:28
Part com.gini.iordache.services.impl.auto.PartServiceImpl.findPartByPartNumber(String) Part does not exists! 04-04-2021 23:53:50